import React from "react";
import DataObjectIcon from "@mui/icons-material/DataObject";
import PropTypes from "prop-types";

import { VBox } from "../Containers";
import { ButtonList } from "../list";
import LabeledIcon from "../LabeledIcon";
import Spacer from "../Spacer";
import CodeWindowChanges from "../../CodeWindowEvents";

LanguageTab.propTypes = {
  selectedLanguage: PropTypes.string.isRequired,
  handleLanguageChange: PropTypes.func.isRequired
};

export default function LanguageTab(props) {
  const languages = [
    "1c",
    "abnf",
    "access",
    "ada",
    "arduino",
    "arm",
    "avr",
    "actionscript",
    "angelscript",
    "apache",
    "applescript",
    "arcade",
    "asciidoc",
    "aspectj",
    "autohotkey",
    "autoit",
    "awk",
    "bash",
    "basic",
    "bnf",
    "brainfuck",
    "c#",
    "c",
    "c++",
    "c/a",
    "cache",
    "cmake",
    "coq",
    "csp",
    "css",
    "cap",
    "clojure",
    "coffeescript",
    "crmsh",
    "crystal",
    "d",
    "dart",
    "delphi",
    "diff",
    "django",
    "dns",
    "dockerfile",
    "dos",
    "dsconfig",
    "dts",
    "dust",
    "ebnf",
    "elixir",
    "elm",
    "erlang",
    "excel",
    "f#",
    "fix",
    "fortran",
    "g-",
    "gams",
    "gauss",
    "gherkin",
    "go",
    "golo",
    "gradle",
    "graphql",
    "groovy",
    "html",
    "http",
    "haml",
    "handlebars",
    "haskell",
    "haxe",
    "hy",
    "ini",
    "inform7",
    "irpf90",
    "json",
    "java",
    "javascript",
    "julia",
    "kotlin",
    "latex",
    "leaf",
    "lasso",
    "less",
    "ldif",
    "lisp",
    "livecode",
    "livescript",
    "lua",
    "makefile",
    "markdown",
    "mathematica",
    "matlab",
    "maxima",
    "maya",
    "mercury",
    "mizar",
    "mojolicious",
    "monkey",
    "moonscript",
    "n1ql",
    "nsis",
    "nginx",
    "nim",
    "nix",
    "ocaml",
    "objective",
    "opengl",
    "openscad",
    "oracle",
    "oxygene",
    "pf",
    "php",
    "parser3",
    "perl",
    "plaintext",
    "pony",
    "postgresql",
    "powershell",
    "processing",
    "prolog",
    "properties",
    "protocol",
    "puppet",
    "python",
    "q",
    "qml",
    "r",
    "reasonml",
    "renderman",
    "renderman",
    "roboconf",
    "ruby",
    "rust",
    "sas",
    "scss",
    "sql",
    "step",
    "scala",
    "scheme",
    "scilab",
    "shell",
    "smali",
    "smalltalk",
    "sml",
    "stan",
    "stata",
    "stylus",
    "subunit",
    "swift",
    "tcl",
    "test",
    "thrift",
    "twig",
    "typescript",
    "vb",
    "vbscript",
    "vhdl",
    "vala",
    "verilog",
    "vim",
    "x++",
    "x86",
    "xl",
    "xquery",
    "yaml",
    "zephir"
  ];

  const { CODE_WINDOW_CHANGES } = CodeWindowChanges;
  return (
    <VBox id="lang-tab" className="tab-item" centered={false}>
      <LabeledIcon label="Language">
        <DataObjectIcon />
      </LabeledIcon>
      <Spacer amount="0.5em" />
      <ButtonList
        orientation="v"
        selected={props.selectedLanguage}
        handleOnClick={event =>
          props.handleLanguageChange(
            CODE_WINDOW_CHANGES.LANGUAGE,
            event.target.innerText
          )
        }
        labels={languages}
      />
    </VBox>
  );
}
